### ISSUE TITLE
Style for anchors

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-valo-theme#1]
_From @heruan on September 1, 2017 16:34_

There's no style for anchor elements like `<a href="#">Awesome link!</a>`. It would be great to have them style with the theme colors instead of the default browser ones!

_Copied from original issue: vaadin/vaadin-themes#49_

**Comment by jouni** [comment]
Thanks, that’s a very valid point. Should be included in the valo/material-colors style module.

**Comment by heruan** [comment]
Great, thank you! I would also remove the underline style when the link is not hovered, to differentiate the hover state (like here in GitHub).

**Comment by jouni** [comment]
Yeah, I briefly thought about that, but for now decided just to affect the colors. If we want to remove the underline, I wasn’t completely sure where I should put those rules. My gut feeling is that they would belong to `typography.html`, part of the `valo-typography` style module.

**Comment by jouni** [comment]
Darn, just noticed it’s not possible to change the opacity of link color between unvisited and visited links due to privacy reasons: https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector

I’ll try to think of another way to set the correct color. Maybe we need to introduce another color just for this :/

**Comment by heruan** [comment]
What about *not* differentiate visited from unvisited links, at all? In my opinion, it's no more what the user expects. I think there are three key factors about styling links:

1. they should be immediately recognizable, so go for the theme primary color;
2. underline them on hover, to express the fact the pointer is ready to trigger the action;
3. be consistent: if the user changes the device, or clears the history, links should not change the color, so it's better to just ignore the visited state and treat them as in 1.

**Comment by jouni** [comment]
Well, I never thought about links that way. But I do agree, the visited style is mostly a relic of a by-gone era nowadays. So I ended up doing just as you proposed, and links are always using the primary color, and only have the underline when hovered. Thanks for the suggestions!

The relevant change: 1586af579c6c1d3a3288a41a9e79566edb966b22
