### ISSUE TITLE
Dialog

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#10]
Valo for Vaadin Elements is getting really great, I hope to see a proper theme for [vaadin-dialog](https://github.com/vaadin/vaadin-dialog) too.

**Comment by jouni** [comment]
Thanks! Theme for vaadin-dialog is coming up as soon as I get combo box and grid done. Should be done within the next 2–3 weeks.

**Comment by heruan** [comment]
Thank you @jouni for the update! Just opened this and the one for the context menu to keep track on them. You know, there are two kinds of people in the world: the ones who like Material, and the ones who have good taste 😄

Go Valo!

**Comment by jouni** [comment]
First version of the dialog theme implemented in e4f07dbd90453d0dbb25a3297e3f3081dd02f20d
