### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#11]
A proper Valo theme for [vaadin-context-demo](https://github.com/vaadin/vaadin-context-menu) would be awesome, too!

**Comment by jouni** [comment]
First iteration now done in b8b6aacd9604602b85a6db2cbca791d9fa505ea1

You can see an example here: https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha1/demo/context-menus.html

The contents of the context menu are not yet part of Vaadin elements, so I didn’t touch those styles yet.

**Comment by jouni** [comment]
Now we have `vaadin-list-box` available, so I change the example to use that. Considering this issue closed (in https://github.com/vaadin/vaadin-valo-theme/commit/7d809eeddabbf06f98f664a02969d78e47cd0998#diff-13d61350fd7db49d7ef6bf72f855039d)
