### ISSUE TITLE
Combo-Box overlay height is incorrect

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-valo-theme#12]
The overlay does not adapt to the number of visible items  but to the available viewport height.

![screen shot 2017-09-19 at 13 39 00](https://user-images.githubusercontent.com/161853/30590673-f255e4da-9d3f-11e7-9900-1955e349cc55.png)

**Comment by jouni** [comment]
I’ve already fixed this locally. Caused by the changes in vaadin-overlay, that the theme should not target the `:host`, but the `part=content` element.
