### ISSUE TITLE
Consider using rem instead of px for font-size

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-valo-theme#16]
Valo theme isn't friendly to people with low vision. Here's why:

![recorded](https://user-images.githubusercontent.com/6059356/31337973-3f0e4dd2-ad06-11e7-859e-505c1a08cbe7.gif)

Related code: https://github.com/vaadin/vaadin-valo-theme/blob/master/typography.html#L10-L16

**Comment by limonte** [comment]
Additional reading:
 
- https://nicolas-hoizey.com/2016/03/people-don-t-change-the-default-16px-font-size-in-their-browser.html
- https://scotch.io/bar-talk/whats-new-in-bootstrap-4#toc-new-unit-rems-for-typography

**Comment by jouni** [comment]
Thanks for the suggestion!

What would it mean in practice? Should we just set  `--valo-font-size: 1rem;` or `--valo-font-size: inherit;`?

I suppose that might be a better default, as developers usually don’t remember to check these things, and we should encourage accessibility. If they want, they can still revert to using a fixed pixel value if they so choose.

**Comment by jouni** [comment]
If we change to using `--valo-font-size: 1rem;`, we should also add the following to the `valo-typography` style module:

```html
html {
  font-size: 16px;
}
```

Or does that also prevent browser settings from overriding it?

**Comment by limonte** [comment]
> If we change to using --valo-font-size: 1rem;, we should also add the following to the valo-typography style module:
>
> html {
>  font-size: 16px;
> }

Please don't! From https://nicolas-hoizey.com/2016/03/people-don-t-change-the-default-16px-font-size-in-their-browser.html

> These default font sizes were set by the device or browser vendors because it was the best size for reading. When you set your font-size in px units, you throw their work to satisfy their users/clients into the bin.

By setting the font-size in px for `html`, you will get the same issue and the "Font size" selector will become useless.
