### ISSUE TITLE
Include a "binder" theme for tabs

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#29]
A common style for tabs on the web is the classic "tab sheet" in binders, where the label of the tab itself is part of the portion of the page it selects. Good examples are the Valo 1 `TabSheet` in FW8 and the GitHub tabs for "Code", "Issues", "Pull requests", etc.

I tried to achieve this with Valo 2 and `vaadin-tabs`: https://jsfiddle.net/heruan/3fcf51ub/1/

But it's rough and I think a supported theme for this would be really appreciated by many!

**Comment by jouni** [comment]
This issue was moved to vaadin/vaadin-tabs#74
