### ISSUE TITLE
Some element features are not visible on low-quality displays

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-valo-theme#35]
When displaying UI in displays not supporting high contrast, certain parts like input in vaadin-text-field are not visible

Here a screenshot of the projector installed in lounge
![img_20171123_131354](https://user-images.githubusercontent.com/161853/33170464-fe4ec5d8-d050-11e7-8dc6-44fe7f51ca53.jpg)

Here the same in thunderbolt display

![screen shot 2017-11-23 at 13 14 12](https://user-images.githubusercontent.com/161853/33170487-124adfae-d051-11e7-99fe-145708e27a08.png)

**Comment by jouni** [comment]
This is unfortunate but expected. The visual style is such that it’s not really possible to make it look nice in both regular displays and in projectors or TVs.

We could offer a high-contrast version of the theme for these situations, or maybe use some media query to use different styles on certain devices.

**Comment by web-padawan** [comment]
FYI: the [Color Contrast analyzer](https://chrome.google.com/webstore/detail/color-contrast-analyzer/dagdlcijhfbmgkjokkjicnnfimlebcll?hl=en) shows the following [output](https://prnt.sc/he7gqr) for preset "Level AA, Small Non-Bold Text (4.5:1)"

Personally, as a short-sighted person, I would suggest using better contrast, especially in Valo demo page sidebar, and also for labels and placeholders. 

See also [color contrast](https://github.com/webcomponents/gold-standard/wiki/Sufficient-Contrast) section in the Web Components Gold Standard checklist.

**Comment by jouni** [comment]
@web-padawan, I agree, thanks for the resources. The demo sidebar has really poor contrast, and I’ll fix that specifically as well.

I have some changes pending in my local repo that should fix some of the contrast issues. I’m using the awesome [contrast-grid](http://contrast-grid.eightshapes.com/) tool for checking the [default color contrast ratios](http://contrast-grid.eightshapes.com/?background-colors=ffffff%2C%200%0D%0AF3F4F5%2C%205%20darken%0D%0AE8EAEC%2C%2010%20darken%0D%0AD4D7DB%2C%2020%20darken%0D%0ABFC4CA%2C%2030%20darken%0D%0AABB1B9%2C%2040%20darken%0D%0A0272F8%2C%20Blue%0D%0AFF432E%2C%20Red%0D%0A00CC63%2C%20Green%0D%0AD2DAE5%2C%20test%0D%0A%0D%0A&foreground-colors=2F4055%2C%20100%0D%0A435164%2C%2090%0D%0A576475%2C%2080%0D%0A6C7787%2C%2070%0D%0A808A97%2C%2060%0D%0A959EA8%2C%2050%0D%0AABB1B9%2C%2040%0D%0ABFC4CA%2C%2030%0D%0AFFFFFF%2C%20White%0D%0A0272F8%2C%20Blue%0D%0AFF432E%2C%20Red%0D%0A00CC63%2C%20Green%0D%0A5D728D%2C%20test%0D%0A&es-color-form__tile-size=compact) (the [dark version](http://contrast-grid.eightshapes.com/?background-colors=2F4055%2C%20Dark%20bg%0D%0A2D3D51%2C%205%20darken%0D%0A2C3B4E%2C%2010%20darken%0D%0A293748%2C%2020%20darken%0D%0A253141%2C%2030%20darken%0D%0A3B4B5F%2C%205%20lighten%0D%0A455467%2C%2010%20lighten%0D%0A586778%2C%2020%20lighten%0D%0A3D92FF%2C%20Blue%0D%0AF95A4B%2C%20Red%0D%0A00CC63%2C%20Green&foreground-colors=FFFFFF%2C%20White%0D%0AF7F8F9%2C%20100%0D%0AE5E8EB%2C%2090%0D%0AD2D5DA%2C%2080%0D%0ABDC3C9%2C%2070%0D%0AAAB1B9%2C%2060%0D%0A959DA9%2C%2050%0D%0A818B99%2C%2040%0D%0A6E7988%2C%2030%0D%0A3D92FF%2C%20Blue%0D%0AF95A4B%2C%20Red%0D%0A00CC63%2C%20Green&es-color-form__tile-size=compact) as well). Those are still with older colors, I’ll have to redo the exercise.

**Comment by jouni** [comment]
@web-padawan, I hope the new version improves the situation. I tried to make the colors comply with 3:1 contrast ratios (or better) in most cases (used the Chrome add-on for testing).

Please take a look: https://cdn.vaadin.com/vaadin-valo-theme/2.0.0-alpha5/demo/

**Comment by web-padawan** [comment]
Thank you @jouni, it does look much better now. Both sidebar and controls contrast is nice to me.

**Comment by jouni** [comment]
I tested the default colors with our office TVs, and all of them worked okay, in my opinion, no obvious contrast issues.

Tested with an old Samsung display (710T S), and there are some problems still. The main issue is the text field style, as the gray background is really light and not very well visible. Though, even Google has similar issues in some of their products (like Drive). I’m probably going to try and tweak the grayscale colors a bit more so that the jump from 5% to 10% is not so drastic, and we could then use 10% for the text field background.

Projectors are definitely still a potential issue, but I’m willing to sacrifice that for a nicer overall look and feel.

**Comment by manolo** [comment]
Could you at least check if it works in the projector at the lounge, I think covering all kind of devices is hard, but at least this might be a reference

**Comment by jouni** [comment]
Yeah, sure, but I’m still skeptical I can do much about it. Maybe we’ll add a hidden feature, that you can toggle some “increased contrast mode” with a special URL parameter 😝

**Comment by jouni** [comment]
> I’m probably going to try and tweak the grayscale colors a bit more so that the jump from 5% to 10% is not so drastic, and we could then use 10% for the text field background.

Did exactly that in 43fe48ce9f7bdb06e54061157f13d598202a3079

**Comment by jouni** [comment]
Let’s reopen an issue in the Lumo styles repo if this is still a concern.
