### ISSUE TITLE
First tab has narrow click area

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-valo-theme#39]
Seems like the first tab has a narrow click area.

![tab-click-area](https://user-images.githubusercontent.com/851745/33426552-879f1880-d5c2-11e7-8006-dd0843a4fb2e.gif)

Also, I noticed a weird behavior on the blue line of the second tab, while clicking (don't know if expected).

**Comment by jouni** [comment]
Thanks, good catch. It’s the prev-button that’s covering the first tab slightly (same thing for the next-button in the other end of the tab bar).

Should set `pointer-events: none` for the hidden buttons (they use opacity transitions, so `display: none` is not good).

The other issue (blue line growing) comes from the keyboard nav styles. A selected tab has that blue line, and when it receives keyboard focus it grows slightly. Though, it should not get applied when interacting with a pointer device, so there’s a small bug there.
