### ISSUE TITLE
Text area should wrap text

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-valo-theme#41]
Currently, `white-space: nowrap` is inherited to text area from text field theme:
![screenshot 2017-12-07 09 22 50](https://user-images.githubusercontent.com/1222264/33703336-52227c38-db30-11e7-8efe-0fa4ff03b8fb.png)

Expected outcome:
![screenshot 2017-12-07 09 24 19](https://user-images.githubusercontent.com/1222264/33703357-6c053974-db30-11e7-9e29-e25d053d5af3.png)

**Comment by jouni** [comment]
Add `white-space: normal;` here: https://github.com/vaadin/vaadin-text-field/blob/next/theme/valo/vaadin-text-area.html#L22

Or should it be `pre-wrap`?

**Comment by platosha** [comment]
Blame me for that line. It should be `pre-wrap`, this is expected and same as in native `<textarea>`.

**Comment by platosha** [comment]
Btw, `pre-wrap` means both: wrapping is enabled, while the linebreaks and whitespace are preserved.

**Comment by jouni** [comment]
Fixed in vaadin-text-field master.
