### ISSUE TITLE
Dark/Light switcher doesn't work

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-valo-theme#8]
https://cdn.vaadin.com/vaadin-valo-theme/0.2.6/demo/

Chrome/Linux

**Comment by heruan** [comment]
Seems like a case-sensitive issue on TinyColor path, #9 should fix this.

**Comment by jouni** [comment]
@limonte, can you check if this actually fixed the issue?

**Comment by heruan** [comment]
@limonte AFAIK the switcher changes the theme of the components shown in their pages, e.g. in https://cdn.vaadin.com/vaadin-valo-theme/0.2.6/demo/buttons.html and it seems working despite the 404 on TinyColor.
